import { describe, expect, it } from 'vitest'
import appSource from './app/App.vue?raw'

describe('App shell contract', () => {
  it('keeps the app-shell runtime boot and teardown behind a dedicated composable', () => {
    expect(appSource).not.toContain('onMounted(() => {\n  shellPersistence.initializeShellPersistence()')
    expect(appSource).not.toContain('onMounted(() => {\n  installOpenDebugLongTaskObserver()')
    expect(appSource).not.toContain('disposeOpenTraceActivitySubscription')
    expect(appSource).not.toContain("mediaQuery?.addEventListener('change'")
    expect(appSource).not.toContain("window.addEventListener('mousedown'")
    expect(appSource).not.toContain("window.removeEventListener('mousedown'")
    expect(appSource).not.toContain('void syncAlterSettingsFromDisk()')
    expect(appSource).not.toContain('onMounted(() => {\n  void workspaceLifecycle.start()')
    expect(appSource).not.toContain('onBeforeUnmount(() => {\n  workspaceLifecycle.dispose()')
    expect(appSource).toContain('useAppShellRuntimeLifecycle')
  })

  it('keeps shell helper implementations out of App.vue', () => {
    expect(appSource).not.toContain('function isTitleOnlyContent(')
    expect(appSource).not.toContain('function documentPathsForPane(')
    expect(appSource).not.toContain('function clearEditorStatusForPaths(')
    expect(appSource).not.toContain('function applyImmediatePathMovesLocally(')
    expect(appSource).not.toContain('function applyDeferredPathMovesLocally(')
  })

  it('uses dedicated shell surface wrappers instead of inlining chrome and overlays', () => {
    expect(appSource).toContain('AppShellChromeSurface')
    expect(appSource).toContain('AppShellWorkspaceSurface')
    expect(appSource).toContain('AppShellOverlays')
    expect(appSource).not.toContain('import TopbarNavigationControls')
    expect(appSource).not.toContain('<TopbarNavigationControls')
    expect(appSource).not.toContain('import SidebarSurface')
    expect(appSource).not.toContain('<SidebarSurface')
    expect(appSource).not.toContain('import WorkspaceStatusBar')
    expect(appSource).not.toContain('<WorkspaceStatusBar')
    expect(appSource).not.toContain('import QuickOpenModal')
    expect(appSource).not.toContain('<QuickOpenModal')
    expect(appSource).not.toContain('import ThemePickerModal')
    expect(appSource).not.toContain('<ThemePickerModal')
    expect(appSource).not.toContain('import WorkspaceEntryModals')
    expect(appSource).not.toContain('<WorkspaceEntryModals')
    expect(appSource).not.toContain('import WorkspaceSetupWizardModal')
    expect(appSource).not.toContain('<WorkspaceSetupWizardModal')
    expect(appSource).not.toContain('import SettingsModal')
    expect(appSource).not.toContain('<SettingsModal')
    expect(appSource).not.toContain('import DesignSystemDebugModal')
    expect(appSource).not.toContain('<DesignSystemDebugModal')
    expect(appSource).not.toContain('import ShortcutsModal')
    expect(appSource).not.toContain('<ShortcutsModal')
    expect(appSource).not.toContain('import AboutModal')
    expect(appSource).not.toContain('<AboutModal')
  })
})
